# coding: utf-8
# This file contains hyperparameter configurations
#
# The variable names listed here must match those in the accompanying config
# file for this model.

batch_size: [8, 16, 32, 64]
lr_decay_factor: [0.94, 0.96, 0.98]
